### ISSUE TITLE
default queue name在集群redis场景中引起频繁报错

### ISSUE THREAD

**Issue by Deeee** [hexindai/egg-bus#13]
报错：BRPOPLPUSH ReplyError: ERR 'BRPOPLPUSH' command keys must in same slot
node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [ 'bull:default:wait', 'bull:default:active', '5' ]
  }
}

原因是集群版lua脚本的使用并不同于单机版，为了保持事务，同一个lua脚本访问应该访问同一个slot，但是redis集群会根据KEY进行hash并取模，因此如果采用默认hash的话，那么就会产生这个错误，解决方案是在key也就是queue的名字上加上{}。

但是在https://github.com/hexindai/egg-bus/blob/fc3e661213a10afe0aadea7f6a4b43ade5ab9f03/lib/bus.js#L20 这一行并没有按照config里传的default name参创建default queue，导致无法用{}解决集群redis hash的问题。

简单来说只要这儿按照config里传的default queue name命名default queue，或者default queue的名字上加上{}，问题就能解决

**Comment by seekcx** [comment]
感谢，这里确实没有取到配置的默认队列名，但是我不确定能不能解决集群问题（暂时没有时间和条件来进行测试），我先发布一个版本，如果有问题欢迎重新打开这个issue。
