### ISSUE TITLE
已处理的，多久会删除？

### ISSUE THREAD

**Issue by male110** [hexindai/egg-bus#17]
我看数据还在redis里，而且没有设置过期时间。多久数据会删除掉？

**Comment by seekcx** [comment]
因为依赖 [bull](https://github.com/OptimalBits/bull) 来实现，可以尝试设置 bull 的 `removeOnComplete` 选项为 `true`。

相关文档 [bull/REFERENCE.md](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md)
