### ISSUE TITLE
大佬 已经给你点Star 请问下 如何通过api获取到当前队列待消费的数量

### ISSUE THREAD

**Issue by 12gameRensheng** [hexindai/egg-bus#26]
问题1 请问下 如何通过api获取到当前队列待消费的数量
问题2 能否配置多个队列 但是 队列名称 不共用一个 
因为我想根据不同的队列 进行设置并发 或 更改redis端口等
![image](https://user-images.githubusercontent.com/45571957/177703049-dff28afb-9afa-42a1-9a52-2f81a9151cf6.png)

**Comment by seekcx** [comment]
第一个问题可以看看 Bull 的文档，使用 `app.bus.get` 方法可以获取 Bull 队列实例；
第二个问题：图上你圈起来的地方就是配置多个队列的地方，默认情况下有一个 `default` 队列，你还可以添加其它队列。在 `job` 和 `listener` 中，都有 `queue` 配置可以为其指定队列名称。

**Comment by 12gameRensheng** [comment]
> 第一个问题：可以看看 Bull 的文档，使用 `app.bus.get` 方法可以获取 Bull 队列实例； 第二个问题：图上你圈起来的地方就是配置多个队列的地方，默认情况下有一个 `default` 队列，你还可以添加其它队列。在 `job` 和 `listener` 中，都有 `queue` 配置可以为其指定队列名称。

哪个api可以获取到 指定队列 待消费的函数名呢

![image](https://user-images.githubusercontent.com/45571957/177705118-7985854e-0fe2-4531-ac03-fa4ec047d226.png)

**Comment by seekcx** [comment]
看一下 Bull 文档吧，我没有研究过这个问题。

**Comment by seekcx** [comment]
队列的操作不是此库的涉及范围，一般来说也不建议直接操作队列。

**Comment by 12gameRensheng** [comment]
谢谢
好的 因为业务中需要配置多个队列
但是每个队列 所占用的资源不一样

**Comment by seekcx** [comment]
嗯，这个库写的有点久了，最新的 bull 我也没有研究过，你可以去看看他的文档，能拿到实例理论上可以得到你要的操作的。

**Comment by 12gameRensheng** [comment]
好 我现在用的也是egg 目前这个库比较合适 谢谢大佬
