### ISSUE TITLE
emit 无法传递 error 对象

### ISSUE THREAD

**Issue by xdliyushen** [hexindai/egg-bus#28]
job1
```js
// ...
async failed(data: any, error: Error) {
    this.app.bus.emit('jobFailed', {
      // 期望在事件中可拿到错误信息
      error,
    });
  }
```

![截屏2022-11-07 下午5 38 34](https://user-images.githubusercontent.com/37898499/200277446-ebddaa78-e072-4704-a59c-9e1698f5a020.png)

jobFailed listener
```js
 async run(event: any) {
  // event.data 中的 error 为空对象
}
```

![截屏2022-11-07 下午5 39 29](https://user-images.githubusercontent.com/37898499/200277633-91652dc8-9f43-4f85-be58-899914fbcaa6.png)

emit 中的 data 并非不能传递复杂对象，似乎是只对 error 对象做了此限制。可否麻烦改下使其能够正常传递 error 对象？

**Comment by seekcx** [comment]
这块限制是 bull 做的，不建议传对象，bull 底层应该会有一个序列化的过程（未求证），很可能会导致数据丢失。

**Comment by xdliyushen** [comment]
这样啊，我的需求是打印log，换个地方打印也可以。
