### ISSUE TITLE
如何监听 job 的 complete 事件？

### ISSUE THREAD

**Issue by xdliyushen** [hexindai/egg-bus#29]
我这里有个执行时间比较长的 job，希望能监听到 bull 的 queue 的 completed 事件，以便在某个 job 完成后再执行下一个 job。请问根据目前的版本有办法实现嘛？

**Comment by xdliyushen** [comment]
补充说明一下，我这里有一个 job，在这个 job 完成之后，会触发另一个 job
```
class Job1 extends Job {
  async run() {
    // 一段耗时的任务

    this.app.bus.dispatch('job2');
  }

  failed() {
    // 任务失败的回调
  }
}
```
目前我碰到的问题是，在执行那段耗时的任务的时候，bull 会认为此 job 执行时间过长，已经失败了（但其实并没有），因此在执行完耗时的任务后，下一个 job 仍会被触发，但同时该 job 的 failed 回调也会被执行。因此我想知道有没有办法监听到某个 job 的 completed 事件

**Comment by seekcx** [comment]
使用 `get` 方法获取 bull 实例操作试试。

**Comment by xdliyushen** [comment]
妥了~
