### ISSUE TITLE
是否可以将bus挂载在agent上?

### ISSUE THREAD

**Issue by mywei1989** [hexindai/egg-bus#30]
考虑一种情况,某任务分为几个步骤,未完整执行完的情况下服务重启了
如何从特定步骤开始重新执行(重试)?
如果只能在worker(app.js)中使用bus对象,在多进程部署情况下还将考虑加锁以避免多worker同时执行.
目前只能通过定时任务 设置type为worker 确保某单一worker执行重试,不过为何要引入定时任务呢.
如果能在agent上发起重试步骤或许可以解决这个问题.
发起了一个[pr https://github.com/hexindai/egg-bus/pull/31]( https://github.com/hexindai/egg-bus/pull/31)
请看看是否可以合并进入

**Comment by seekcx** [comment]
首先，多进程的问题是由 bull 来保证的

我无法确定 agent 的方式可以解决你所说的步骤问题，但是增加对 agent 的支持本身符合 egg 插件的设计规范，所以我稍后会合并这个。
