### ISSUE TITLE
不影响请求，队列任务执行的过程中不阻塞请求

### ISSUE THREAD

**Issue by gakkiox** [hexindai/egg-bus#33]
大佬，请教一下，怎么能实现，队列任务执行的过程中不阻塞请求， 就是相当于任务变成后台任务

**Comment by gakkiox** [comment]
有没有 项目例子什么的

**Comment by seekcx** [comment]
目前的设计似乎无法实现，因为已经有很长一段时间没有使用egg了，没有精力去维护和验证，欢迎提pr。
