### ISSUE TITLE
请问你是怎么处理多次重试失败job

### ISSUE THREAD

**Issue by jasonLaw1015** [hexindai/egg-bus#4]
例如：因为数据库短时不可用的原因导致job多次重试不可用， 现在修复好数据库后。然后怎样去重试这些失败后的job。有什么好的建议吗？你们是怎么处理类似的问题的？

感谢大佬！！！

**Comment by seekcx** [comment]
在 job 失败达到指定次数之后，会回调 failed 方法，可以在这个方法里将 job 的数据暂时保存在一个失败任务表里，通过 scheudle 定时检查失败任务表中的数据，重新放入 job。

**Comment by jasonLaw1015** [comment]
> 在 job 失败达到指定次数之后，会回调 failed 方法，可以在这个方法里将 job 的数据暂时保存在一个失败任务表里，通过 scheudle 定时检查失败任务表中的数据，重新放入 job。

好的，感谢
