### ISSUE TITLE
Job 和 Listener 的区别？

### ISSUE THREAD

**Issue by shiny** [hexindai/egg-bus#5]
除了调用方式和目录不一样，Job 和 Listener 的区别是什么？
什么场景下适合使用 Job，什么场景下适合使用 Listener？
最佳实践是什么？

**Comment by seekcx** [comment]
listener 可以简单的理解为多个 job 的集合。

listener 可以解耦主线业务产生的附加任务。比如注册，只需要抛出一个注册成功的事件，而不用关心具体会执行什么任务，监听这个事件的 listener 可能有多个（发送短信、发送邮件、推送统计数据等）。

而 job 只是单个耗时任务，在主线业务明确知道需要执行哪些任务的情况下使用。

**Comment by shiny** [comment]
感谢释疑
