### ISSUE TITLE
不是用 TypeScript 构建的 egg 项目可以使用吗

### ISSUE THREAD

**Issue by xiaoxiunique** [hexindai/egg-bus#8]

**Comment by seekcx** [comment]
可以的。文档也是按 JS 写法编写的。

**Comment by xiaoxiunique** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "abel"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午2:24
收件人: "hexindai/egg-bus"<egg-bus@noreply.github.com&gt;; 
抄送: "929746602"<929746602@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hexindai/egg-bus] 不是用 TypeScript 构建的 egg 项目可以使用吗 (#8)





 
可以的。文档也是按 JS 写法编写的。
